import {
  AlertCircle,
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  Circle,
  CircleX,
  ClipboardList,
  Clock,
  Copy,
  Crown,
  Download,
  Eye,
  EyeOff,
  FileText,
  Globe,
  GraduationCap,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Lightbulb,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  Moon,
  Package,
  Paperclip,
  Pencil,
  Plus,
  QrCode,
  RefreshCw,
  School,
  Search,
  Send,
  ShieldCheck,
  Sun,
  Ticket,
  Trash2,
  TriangleAlert,
  Unlock,
  Upload,
  User,
  Users,
  Video
} from 'lucide-react';

const ICONS = {
  alert: AlertCircle,
  arrowRight: ArrowRight,
  analytics: BarChart3,
  bell: Bell,
  book: BookOpen,
  bot: Bot,
  building: Building2,
  calendar: Calendar,
  check: Check,
  checkCircle: CheckCircle2,
  clipboard: ClipboardList,
  clock: Clock,
  copy: Copy,
  crown: Crown,
  download: Download,
  eye: Eye,
  eyeOff: EyeOff,
  file: FileText,
  globe: Globe,
  graduation: GraduationCap,
  help: HelpCircle,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  key: KeyRound,
  landmark: Landmark,
  lightbulb: Lightbulb,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  mapPin: MapPin,
  megaphone: Megaphone,
  menu: Menu,
  message: MessageCircle,
  moon: Moon,
  package: Package,
  paperclip: Paperclip,
  pencil: Pencil,
  plus: Plus,
  qr: QrCode,
  refresh: RefreshCw,
  school: School,
  search: Search,
  send: Send,
  shield: ShieldCheck,
  sun: Sun,
  ticket: Ticket,
  trash: Trash2,
  warning: TriangleAlert,
  unlock: Unlock,
  upload: Upload,
  user: User,
  users: Users,
  video: Video
};

export default function AppIcon({ name, size = 18, strokeWidth = 2, style, ...props }) {
  const Icon = ICONS[name] || Circle;
  return (
    <Icon
      aria-hidden="true"
      focusable="false"
      size={size}
      strokeWidth={strokeWidth}
      style={{ flexShrink: 0, ...style }}
      {...props}
    />
  );
}
